<?php

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

return array(
    'Primer Cuadro (Centro)',
    'Miguel Hidalgo',
    'ISSSTESIN',
    'Las Fuentes 2000',
    'Benito Juárez',
    'Reyes Guerrero',
    'Las Malvinas',
    'Bugambilias',
    'Gaviotas',
    'Narciso Mendoza',
    'Prof. Conrado Espinoza',
    'Sector Fátima',
    'Jiquilpan',
    'Jordan',
    'Las Fuentes',
    'Deportivo y Rincón',
    'Juan Cota',
    'Ávila Corona',
    'Sanchez Ruiz',
    'Jardines de Fátima',
    'Fovissste',
    'Privada Palladio',
    'Macapule Infonavit',
    'Residencial Campestre',
    'Bosques Del Country',
    'Viñedos Residencial',
    'Privada Toscana',
    'Daniel Biul Ruelas',
    'Palos Verdes Infonavit',
    'Jiquilpan',
    'Tepeka',
    'Residencial Diamante',
    'Fuentes Del Bosque',
    'Diamantes 2a Sección',
    'Jardín',
    'Libertad',
    'Ruben Jaramillo',
    'México',
    'Flor de las Arboledas',
    'Luis Donaldo Colosio',
    'Providencia',
    'Nuevo Horizonte',
    'Valle Cañaveral',
    'Los Sabinos',
    'FOVISSSTE 3',
    'Residencial Palmira',
    'El Chamizal',
    'Del Real',
    '75 (Heriberto Valdez Romero)',
    'Santa Fe',
    'Valle Bonito',
    'Carolina Residencial',
    'Bosques del Pedregal',
    'San Francisco',
    'Alfonso G Calderón',
    '10 de Mayo',
    'Estrella',
    'Adolfo Lopez Mateos',
    '28 de Junio',
    'Scally',
    'Jordan Jiquilpan',
    'Valentín Gutiérrez',
    'Ibarra',
    'Julia Viuda de Ríos',
    'Popular Blanca Gastelum',
    'Zaky Muez',
    'Mario Avilez',
    'Alfredo Salazar',
    'Alma Guadalupe Estrada',
    'Dolores Castro',
    'Mayra H Pamplona',
    'Germán Arroyo',
    'Las Torres',
    'Ernesto Hays Borbo',
    'Toledo Ceballos',
    'Jardines Del Valle',
    'Jardines Del Sol',
    'Jordan Madero',
    'Gastelum',
    'Ofelia Duarte',
    'Deportivo Country Club',
    'Grijalva',
    'Bachomo Infonavit',
    'Los Pinos',
    'Islas Residenciales',
    'Los Sauces',
    'Álamo',
    'Cuauhtémoc',
    'Jardines del Country',
    'Álamos',
    'Jardines del Bosque',
    'Los Olivos',
    'Primavera',
    'Monico Soto',
    'Del Carmen',
    'Monferrat',
    'Residencial del Country',
    'Real del Country',
    'Bosque del Real',
    'Álamos I',
    'Álamos II',
    'U.A.S. Álamos',
    'Lastras Altamirano',
    'Las Palmas',
    'Residencial Del Valle',
    'Teresita',
    'Progresivo San Rafael',
    'Menonitas',
    'INFONAVIT Mochicahui II',
    'Jardines de Zacatecas',
    'Villas del Sol',
    'La Cuchilla',
    'Centro Plaza Mochis',
    'Loma Dorada',
    'La Memoria',
    'Mallorca',
    'Versalles Residencial',
    'Parque Industrial Ecológico',
    'Monte Carlo',
    'Zona Industrial',
    'Ingeniero Heriberto Valdez Romero',
    'Lázaro Cárdenas',
    'Central de Abastos',
    'Bellavista',
    'Villa Huites',
    'FOVISSSTE Tabachines IV',
    'Jiquilpan 2',
    'INFONAVIT Mochicahui',
    'Tabachines',
    'Roberto Perez Jacobo',
    'Villa Owen',
    'Del Parque',
    'Hacienda Santa Clara',
    'Alejandro Peña',
    'Rosendo G Castro',
    'Realito',
    'La Esperanza',
    'Las Mañanitas',
    'Valle Verde',
    'Real Aurora',
    'Las Glorias',
    'Santa Lourdes',
    'Prados del Valle',
    'Santa Rosa',
    'Residencial Aurora',
    'Ferrocarril',
    'Residencial Ahome 2000',
    'Quinta de Cortes',
    'Gabriel Leyva',
    'Margarita',
    'Jardines de Guadalupe',
    'Villa de Cortes',
    'Terranova',
    'San Fernando',
    'Conquistadores',
    'Villas Monterrey',
    'Los Naranjos',
    'Residencial Platino',
    'Campanario',
    'Paseo de las Aves',
    'Las Huertas II',
    'Salvador Esquer Apodaca',
    'Las Quintas',
    'Las Huertas',
    'Real del Valle',
    'Tulipanes',
    'Villa Fontana',
    '12 de Octubre',
    'San Fernando',
    'Sierra Bonita',
    'Santa Cecilia',
    'Azucena',
    'Santa Teresa',
    'Álamos Country',
    'Residencial Paseo Alameda',
    'Zafiro',
    'Santa Bárbara',
    'Paseo Alameda',
    'Portal de Hierro',
    'Las Villas Residencial',
    'Villa de Cortez',
    'Quinta Real',
    'Haciendas Country',
    'Las Delicias',
    'Hacienda del Arroyo',
    'Palmera Residencial',
    'Las Haciendas',
    'Hacienda Arroyo Pioneros',
    'Valle de la Rosa',
    'Alcázar del Country',
    'Francisco Villa',
    'Owen',
    'San José',
    'Santa María',
    'Santa Alicia',
    'Cedros',
    'Colon',
    'El Dorado',
    'Los Virreyes',
    'La Esmeralda',
    'Santa Catalina',
    'San Isidro',
    'Valle del Rey',
    'Urbi Villa del Rey',
    'Anáhuac',
    'Bienestar',
    'Insurgentes Obrera',
    'Obrera',
    'Independencia',
    'Vivienda Popular',
    'Sinaloa',
    'Antonio Toledo Corro',
    'Raul Romanillo',
    'STASE Los Álamos',
    'Francisco Labastida Ochoa',
    'La Joya',
    'La Florida',
    'Residencial Mar de Cortés',
    'Las Isabeles',
    'Tulipanes',
    'Universitario',
    'Prados del Sur',
    'STASE IV',
    'La Herradura',
    'Parque Sinaloa',
    'Americana',
    'Burócrata',
    'Morelos',
    'Lopez Portillo',
    'Ampliación Burócrata',
    'Real de Santiago',
    'Pradera de Villa',
    'Las Misiones',
    'Mediterráneo',
    'Las Nubes',
    'Real de Villa',
    'Villa Centenario',
    'Jardines de Villa',
    'Villa de Santiago',
    'Montebello',
    'Privanzas',
    'Prado Bonito',
    'Los Laureles',
    'Siglo XXI',
    'Jardines de Morelos',
    'Nueva Revolución',
    'Almendras',
    'Lázaro Cárdenas Del Rio',
    'Catarinas',
    'Nuevo Siglo',
    'Las Flores',
    'Ampliación Nuevo Siglo',
    'Prados III',
    'Camelias',
    'Primavera CTELL 11',
    'Las Cerezas',
    'Jardines de Primavera',
    'Niños Héroes',
    'La Cantera',
    'Los Girasoles',
    'Las Cañas',
    'Las Praderas',
    'Morelos CTM',
    'Morelos CTM 2',
    'Santa Luz',
    'Los Ángeles',
    'San Francisco',
    'Los Portales',
    'Huatabampito',
    'Mayocoba',
    'Campo Gastelum',
    'Tozalibampo',
    'Tabelojeca',
    'Agua Nueva',
    'San Miguel Zapotitlan',
    'Club de Leones',
    'Sector Juricahui',
    'Paroscahui',
    'Nuevo San Miguel',
    'Bacaporobampo',
    'Choacahui',
    'Bajada de San Miguel',
    'Las Calaveras',
    'Vallejo (Porvenir Vallejo)',
    'Los Goros',
    'Flor Azul',
    'Gabriel Leyva Solano (Zapotillo Dos)',
    'Goros 2',
    'El Porvenir',
    'Bagojo del Río (Bombas Aguilas)',
    'Cachoana',
    'Zapotillo 1',
    'Águila Azteca',
    'Macapule',
    'Bolsa de Tosalibampo 1',
    'Bagojo Colectivo',
    'Emiliano Zapata',
    'Cuchilla de Cachoana',
    'Los Suárez',
    'El Guayabo',
    'Cohuibampo',
    'Puesta de Sol',
    'Ahome Centro',
    'La Florida',
    'Las Bombitas',
    'Inzunza',
    'Melchor Ocampo',
    'Benito Juárez',
    'Guadalupe',
    'San Antonio',
    'Morelos',
    'Individual Ahome',
    'Hidráulica',
    'Ahome Independencia',
    'Antonio Toledo Corro',
    'La Despensa',
    'El Refugio',
    'Huacaporito',
    'San Pablo',
    'La Capilla',
    'Gloria Ochoa de Labastida',
    'Higueras de Zaragoza Centro',
    'San Lorenzo Nuevo',
    'Magisterial',
    'Hidráulica',
    'Ejidal',
    'Buenavista',
    'Francisco Ceballos',
    'San Isidro',
    'Nueva',
    'Las Lajitas',
    'Jitzamuri',
    'Bolsa de Tozalibampo Dos',
    'San Lorenzo Viejo',
    'Los Algodones',
    'San José de Ahome',
    'El Aguajito',
    'Poblado 5',
    'Chihuahuita',
    'Poblado 6 (Los Natoches)',
    'Mártires de Sinaloa',
    'Gral. Guillermo Chavez Talamantes',
    'Niños Héroes de Chapultepec',
    'Gustavo Diaz Ordaz',
    'Revolución Mexicana',
    'Venustiano Carranza',
    'Emigdio Ruiz',
    'Alfonso G. Calderón (Poblado Siete)',
    'Bacorehuis',
    'Dolores Hidalgo',
    'Sinaloa de Leyva',
    'Las Grullas Margen Derecho',
    'El Colorado',
    'Las Grullas Margen Izquierdo',
    'El Alhuate',
    'La Florida',
    'El Bule',
    'Dieciocho de Marzo',
    'Felipe Angeles',
    'Cerrillos (campo 35)',
    'Cereso Nuevo',
    'Compuertas O 21 de Septiembre',
    'Rosendo G Castro',
    '5 de Mayo',
    'Campo La Arrocera',
    'Los Mochis',
    '20 de Noviembre Viejo',
    '20 de Noviembre Nuevo',
    'Ricardo Flores Magón',
    'Louisiana',
    'Plan de San Luis',
    'Albergue Louisiana',
    'Santa Bárbara (Cabaihunaca)',
    'Los Mochis (Los Mochis)',
    'Atardeceres',
    'Topolobampo Centro',
    'Topolobampo',
    'Correos',
    'Secundaria',
    'Plaza',
    'Estación 1',
    'Aduana',
    'Capilla San José',
    'San José 1',
    'San José 2',
    'El Pedregal',
    'Kilómetro 23',
    'Pestalozzi',
    'Varadero 1',
    'Varadero 2',
    'Sindicatura',
    'Banamex',
    'Seguro Social',
    'Los Conchos',
    'Pérgola 1',
    'Pérgola 2',
    'Providencia',
    'Mendez',
    'Secretaria de Marina',
    'Sindicato',
    'Barrio Estándar',
    'Telmex',
    'Pesquera',
    'Secretaria de Marina Bajos',
    'Iglesia de Guadalupe',
    'CET Mar',
    'La Guasima',
    'Estación 2',
    'INFONAVIT La Curva',
    'Cartolandia',
    '24 de Febrero',
    'Ohuira',
    'Paredones',
    'Bachomobampo 1',
    'Bachomobampo 2',
    '9 de Diciembre',
    'Plan de Guadalupe',
    'Plan de Ayala (Campo Cinco)',
    'Benito Juárez',
    'Los Batequis',
    'Primero de Mayo',
    'El Estero',
    'Lázaro Cárdenas (Muellecito)',
    'Carrizo Grande'
);